export const types = {
    authLogin: '[auth] Login',
    authLogOut: '[auth] LogOut',
    authValidate: '[atuh] Validate',
    dataGet: '[Data] Get',
    dataGetState: '[Data] Get State',
    dataSetActive: '[Data] Set Active',
    dataResetActive: '[Data] Reset Active',
    dataCreate: '[Data] Create',
    dataUpdate: '[Data] Update',
    dataDelete: '[Data] Delete',
    dataReset: '[Data] Reset',
    instructorsGet: '[Instructors] Get',
    instructorsGetState: '[Instructors] Get State',
    instructorsSetActive: '[Instructors] Set Active',
    instructorsResetActive: '[Instructors] Reset Active',
    instructorsCreate: '[Instructors] Create',
    instructorsUpdate: '[Instructors] Update',
    instructorsDelete: '[Instructors] Delete',
    tableSetParameters: '[Table] Set Parameters',
    tableResetParameters: '[Table] Reset Parameters'
}