export const types = {
    authLogin: '[auth] Login',
    authLogOut: '[auth] LogOut',
    authValidate: '[atuh] Validate',
    coursesGet: '[Courses] Get',
    coursesGetState: '[Courses] Get State',
    coursesSetActive: '[Courses] Set Active',
    coursesResetActive: '[Courses] Reset Active',
    coursesCreate: '[Courses] Create',
    coursesUpdate: '[Courses] Update',
    courseDelete: '[Courses] Delete',
    instructorsGet: '[Instructors] Get',
    instructorsGetState: '[Instructors] Get State',
    instructorsSetActive: '[Instructors] Set Active',
    instructorsResetActive: '[Instructors] Reset Active',
    instructorsCreate: '[Instructors] Create',
    instructorsUpdate: '[Instructors] Update',
    instructorsDelete: '[Instructors] Delete',
    tableSetParameters: '[Table] Set Parameters',
    tableResetParameters: '[Table] Reset Parameters'
}